export const lang = [
  {
    appname: 'Japa Mala',
    label: 'Select Language',
    selectlanguage: 'Select Language',
    setyourtarget: 'Set Your Target',
    default: 'Default',
    malabeads: 'Mala Beads',
    save: 'Save',
    meditaionsofar: 'Meditation So Far',
    totalcount: 'Total Count',
    target: 'Target',
    beadcont: 'Beads Count',
    malascomp: 'Mala Completed',
    timeforcomp: 'Time estimation for completion',
    reset: 'Reset',
    resetm: 'Reset',
    warning: 'Warning: Setting new target resets all counters to Zero.',
    youare: 'You are',
    goalaway: 'malas away from your goal',
    Moksha: 'Moksha',
    help: 'Help',
    Ok: 'Ok',
    begin: 'Begin',
    home: 'Home',
    edit: 'Edit',
    helphead: 'Welcome to the Japa Mala',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'Elapsed Time',
    more: 'More Apps',
    web: 'Web Apps',
    tnc: 'Apps Policy',
    info: 'About',
    share: 'Share',
    settings: 'Settings',
    appshead: 'Apps Privacy Policy',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'Cannot estimate goal time now',
    snack1: 'Japa Mala\n Minimum number of beads is 11',
    snack2: 'Japa Mala\n Minimum Target is 108',
    cancel: 'Cancel',
    dismiss: 'Dismiss',
    warning1: 'You have completed your target\n resetting to zero',
    settingssave: 'Settings Saved!',
    ahe: '',
  },
  {
    appname: 'जपमाला',
    label: 'मराठी',
    selectlanguage: 'Select Language(भाषा निवडा)',
    setyourtarget: 'आपले लक्ष्य',
    default: 'डिफ़ॉल्ट',
    defaultm: 'मण्यांची किमान संख्या',
    malabeads: 'मणी',
    save: 'जतन',
    meditaionsofar: 'आतापर्यंत चे ध्यान',
    totalcount: 'एकूण संख्या',
    target: 'लक्ष्य',
    beadcont: 'मणी मोजणे',
    malascomp: 'पूर्ण झालेल्या माळा',
    timeforcomp: 'तुमचे ध्येय गाठण्यासाठी अंदाजे वेळ',
    reset: 'रीसेट',
    resetm: 'ठीक आहे',
    warning: 'सूचना: नवीन लक्ष्य सेट केल्याने सर्व काउंटर शून्य करते.',
    youare: 'तुम्ही तुमच्या ध्येयापासून',
    goalaway: 'मणी दूर आहात',
    Moksha: 'मोक्ष',
    help: 'मदत',
    Ok: 'ठीक',
    begin: 'प्रारंभ',
    home: 'होम',
    edit: 'संपादित करा',
    helphead: 'ध्यान ट्रॅकर अ‍ॅपमध्ये आपले स्वागत आहे!',
    para1:
      'या अ‍ॅपची मदतीचा वापर करून आपल्याच्या ध्यानाचा प्रगतीचे ट्रॅक करण्यात मदती करतो. नियमित लक्ष्य 1,00,000 (एक लाख) नियुक्त केल्या आहे, आणि मालातील वाळंब्यांची संख्या 108 नियुक्त केली आहे. आपण पसंदीदा लक्ष्य आणि माला वाळंब्यांची कांटी संख्या आपल्याच्या सेटिंग्ज स्क्रीनवर विविधता देऊन आपल्याची आवडतील लक्ष्ये आणि माला वाळंब्यांची संख्या सोडवू शकता. ज्येवेळेच आपण ईन्ही अंक मंथन करता त्येवेळेच अ‍ॅप आपल्याच्या लक्ष्यात प्राप्त करण्याच्या अनिवार्य मालांची कुल संख्या कंप्यूट करते.',
    para2:
      'जेव्हा आपण आपल्या ध्यानाचा सुरुवात करता तेव्हा टाइमर स्वयंचलितपणे सुरू होतो. जर आपल्याला विश्रांतीची आवड आहे, तर फक्त पॉज बटणावर टॅप करा. जेव्हा आपल्याला आपल्या ध्यानाची पुनरारंभी आवडते तेव्हा टाइमर स्वयंचलितपणे पुन्हा सुरू होईल. जर आपल्याला दिवसाच्या शेवटच्या असल्यास, तर बॅक बटणावर टॅप करून परत जाण्याच्या आवडत्या प्रारंभ स्क्रीनला परत जाऊ द्या, ज्यात आपल्याच्या ध्यानाच्या प्रगतीच्या आंकडा दाखवल्या जातात. हे ती आपल्याच्या औसत ध्यान अवधीवर आपल्याच्या लक्ष्यात प्राप्त करण्याच्या शेष वेळाची अंदाज देते.',
    para3:
      'अ‍ॅप आपल्याला आपल्याच्या आंखांची बंद केलेल्या स्थितीत ध्यान करण्याची अनुमती देते. एक बीपची आवाज किंवा एक वेगळी टोन एक माला पूर्ण झाल्याची सूचना देतात, आणि बंद झाल्याची सूचना देते की आपल्याला आपल्या लक्ष्याकडून प्राप्त झाल्याची सूचना देते. मालांची संख्या हमेशा मुख्य स्क्रीनवर दाखवली जाते.',
    para4:
      'ध्यानाच्या जगात आपले स्वागत आहे! आंतरिक शांतता आणि उपासनेच्या दिशेने आपल्याच्या प्रयाणाची सुरवात करा.',
    elapsed: 'साधनेचा वेळ',
    more: 'अजून अॅप्स',
    web: 'वेब अ‍ॅप्स',
    tnc: 'अॅप्स धोरण',
    info: 'अॅप्स संबांधित ',
    share: 'इतरांना द्या',
    settings: 'सेटिंग्ज',
    appshead: 'अॅप्स धोरण',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'तुमच्या ध्येयाच्या वेळेचा अंदाज आत्ता लावू शकत नाही.',
    snack1: 'जप माला\n 11 वर्षीय आवश्यक असलेली किंमत',
    snack2: 'जप माला\n 108 वर्षीय नियमितीस आवश्यक आहे',
    cancel: 'रद्द करा',
    dismiss: 'ठीक आहे',
    warning1: 'तुम्ही आपल्या उद्देश्याला पूर्ण केलं आहे\n निरूपणात आणता येईल',
    settingssave: 'सेटिंग्ज सेव्ह केली!',
    ahe: 'आहे',
  },
  {
    label: 'भाषा चुनें',
    selectlanguage: 'Select Language(भाषा चुनें)',
    setyourtarget: 'अपना लक्ष्य',
    default: 'डिफ़ॉल्ट',
    defaultm: 'मानकों की न्यूनतम संख्या ',
    malabeads: 'मनका',
    save: 'जतन',
    meditaionsofar: 'अब तक का ध्यान',
    totalcount: 'कुल गिनती',
    target: 'लक्ष्य',
    beadcont: 'मनका गिनती',
    malascomp: 'पूर्ण हुई मालाए',
    timeforcomp: 'अपने लक्ष्य तक पहुंचने का अनुमानित समय',
    reset: 'रीसेट',
    resetm: ' ठीक है',
    warning:
      'चेतावनी: नया लक्ष्य निर्धारित करने से सभी काउंटर शून्य हो जाते हैं।',
    youare: 'आप अपने लक्ष्य से ',
    goalaway: 'माला दूर हैं',
    Moksha: 'मोक्ष',
    help: 'मदद',
    Ok: 'ठीक',
    begin: 'आरंभ',
    home: 'होम',
    edit: 'समायोजन',
    helphead: 'ध्यान ट्रैकर ऐप में आपका स्वागत है!',
    para1:
      'यह ऐप आपकी ध्यान प्रगति का ट्रैक करने में मदद करता है। डिफ़ॉल्ट लक्ष्य १,००,००० (एक लाख) पर सेट किया गया है, और माला में बीड्स की संख्या १०८ रखी गई है। आप सेटिंग्स स्क्रीन पर अपने पसंदीदा लक्ष्य और माला बीड्स गिनती को अनुकूल कर सकते हैं। जब आप इन आंकड़ों को संशोधित करते हैं, ऐप तुरंत आपके लक्ष्य को प्राप्त करने के लिए आवश्यक मालाओं की कुल संख्या की गणना करता है।',
    para2:
      'जब आप अपना ध्यान शुरू करते हैं, तो टाइमर स्वचालित रूप से चालू होता है। यदि आपको विश्रांति की आवश्यकता है, तो बस पॉज़ बटन दबाएं। जब आप अपना ध्यान दोबारा शुरू करते हैं, तो टाइमर स्वचालित रूप से फिर से शुरू हो जाएगा। यदि आप दिन के लिए समाप्त हो गए हैं, तो वापस जाने के लिए बैक बटन दबाएं, जिसमें आपकी ध्यान साधना की प्रगति के सांख्यिकी दिखाई देती है। यह आपकी औसत ध्यान अवधि के आधार पर आपके लक्ष्य को पूरा करने के लिए शेष समय का अनुमान भी देता है।',
    para3:
      'ऐप आपको आपके आंखें बंद करके ध्यान करने की अनुमति देता है। एक बीप की आवाज़ द्वारा सूचित किया जाता है कि एक माला पूरी हो गई है, और एक विभिन्न ध्वनि द्वारा सूचित किया जाता है कि आपने अपना लक्ष्य प्राप्त कर लिया है। पूरी हुई माला की गिनती हमेशा मुख्य स्क्रीन पर दिखाई देती है।',
    para4:
      'ध्यान की दुनिया में आपका स्वागत है! आंतरिक शांति और सजगता की ओर अपनी यात्रा शुरू करें।',
    elapsed: 'साधना समय',
    more: 'और ऐप',
    web: 'वेब ऐप्स',
    tnc: 'ऐप्स नीति',
    info: 'अॅप्स संबांधित',
    share: 'इतरांना द्या',
    settings: 'सेटिंग्स',
    appshead: 'गोपनियता',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'अभी अपने लक्ष्य के समय का अनुमान नहीं लगाया जा सकता।',
    snack1: 'जपमाला\n 11 मनी की न्यूनतम संख्या है',
    snack2: 'जपमाला\n 108 का न्यूनतम लक्ष्य है',
    cancel: 'रद्द करें',
    dismiss: 'ठीक है',
    warning1: 'आपने अपना लक्ष्य पूरा किया है\n शून्य पर रीसेट किया जा रहा है',
    settingssave: 'सेटिंग सहेजी गई!',
    ahe: 'है',
  },
  {
    appname: 'જપમાલા',
    label: 'ભાષા પસંદ કરો',
    selectlanguage: 'ભાષા પસંદ કરો',
    setyourtarget: 'તમારું લક્ષ્ય',
    default: 'મૂળભૂત',
    malabeads: 'માળા બીડ્સ',
    save: 'સાચવો',
    meditaionsofar: 'ધ્યાન અત્યંત',
    totalcount: 'કુલ ગણાય',
    target: 'લક્ષ્ય',
    beadcont: 'માળાના બીડ્સ',
    malascomp: 'માળા પૂર્ણ થયો',
    timeforcomp: 'પૂર્ણ થવાનો સમય અંદાજ',
    reset: 'રીસેટ',
    warning: 'ચેતવણી: નવો લક્ષ્ય સેટ કરવાથી તમામ ગણતરીઓ શૂન્ય થયો છે.',
    youare: 'તમે',
    goalaway: 'તમારા લક્ષ્યથી માળા દૂર છો',
    Moksha: 'મોક્ષ',
    help: 'મદદ',
    Ok: 'ઠીક છે',
    begin: 'શરૂ',
    home: 'ઘર',
    edit: 'ફેરફાર કરો',
    helphead: 'ધ્યાન ટ્રેકર એપ્લિકેશનમાં આપનું સ્વાગત છે!',
    para1:
      'આ એપ્લિકેશન તમારી ધ્યાન પ્રગતિને ટ્રેક કરવામાં મદદ કરે છે. મૂળભૂત લક્ષ્ય 1,00,000 (એક લાખ) પર સેટ કર્યો છે, અને માળામાંના બીડ્સની સંખ્યા 108 પર સેટ કર્યી છે. તમે સેટિંગ્સ સ્ક્રીન પર તમારો પસંદીદો લક્ષ્ય અને માળાના બીડ્સની સંખ્યાને કસ્ટમાઇઝ કરી શકો છો. આ એપ્લિકેશન તમારો લક્ષ્ય પ્રાપ્ત કરવાની માટે જ્યારેતે આ આંકડાઓને સંશોધી છો ત્યારે તમારી પાસેથી આવશ્યક માળાઓની કુલ સંખ્યાને તત્વને કરે છે.',
    para2:
      'જ્યારે તમે તમારું ધ્યાન શરૂ કરો છો, ત્યારે ટાઇમર ઓટોમેટિક રીતે ચાલશે. જો તમારી વિશ્રામની આવશ્યકતા હોય, તો ફક્કો બટન દબાવો. જ્યારે તમે તમારો ધ્યાન ફરીથી શરૂ કરો છો, ત્યારે ટાઇમર ઓટોમેટિક રીતે મળશે. જો તમે દિવસ માટે સમાપ્ત થયા છો, તો પીછેનું બટન દબાવીને પ્રવેશ સ્ક્રીનને પરત જવાની જરૂર છે, જે તમારી ધ્યાન પ્રગતિનો આकર્ષક આંકડા દર્શાવે છે. તે તમારા લક્ષ્ય પ્રાપ્ત કરવાનો બાકી સમયનો અંદાજ પણ આપે છે, તમારી ઔસત ધ્યાન અવધિને આધાર રાખીને.',
    para3:
      'આ એપ્લિકેશન તમને આપની આંખો બંધ કરીને ધ્યાન કરવાની મંજૂરી આપે છે. માળાનું પૂર્ણતાને સૂચિત કરવા માટે એક બીપ ધ્વનિનો ઉપયોગ કરે છે, અને આંય ધ્વનિનો ઉપયોગ કરે છે કે તમે તમારો લક્ષ્ય પ્રાપ્ત કર્યો છો. પૂર્ણ થયેલ માળાની ગણતરી હંમેશા મુખ્ય સ્ક્રીન પર દર્શાવાય છે.',
    para4:
      'ધ્યાન દુનિયામાં આપનું સ્વાગત છે! આપની આંતરિક શાંતિ અને સજગતાની યાત્રા શરૂ કરો.',
    elapsed: 'કામ થયેલ સમય',
    more: 'વધુ એપ',
    web: 'વેબ એપ્લિકેશન્સ',
    tnc: 'એપ નીતિ',
    info: 'વિગતો',
    share: 'શેર કરો',
    settings: 'સેટિંગ્સ',
    appshead: 'એપ્લિકેશન્સ ગોપન નીતિ',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'હમણાં લક્ષ્ય સમય આંકવું શક્ય નથી.',
    snack1: 'જપા માળા\n 11 અથવા તેના નીચેના મણ્યોની મિનિમમ સંખ્યા 11 છે',
    snack2: 'જપા માળા\n ન્યૂનતમ લક્ષ્ય 108 છે',
    cancel: 'રદ કરો',
    dismiss: 'ખારીજ કરો',
    warning1: 'તમે તમારું લક્ષ્ય પૂરુ કર્યું છે\n શૂન્ય પર રીસેટ કરવામાં આવશે',
    settingssave: 'સેટિંગ્સ સેવ કરી!',
    ahe: '',
  },
  {
    label: 'বাঙালি',
    selectlanguage: 'Select Language(ভাষা নির্বাচন করুন)',
    setyourtarget: 'আপনার লক্ষ্য নির্ধারণ করুন',
    default: 'ডিফল্ট',
    malabeads: 'মালা হালুদ',
    save: 'সংরক্ষণ',
    meditaionsofar: 'এখন পর্যন্ত ধ্যান',
    totalcount: 'মোট গণনা',
    target: 'লক্ষ্য',
    beadcont: 'মালা হালুদের সংখ্যা',
    malascomp: 'মালা সমাপ্ত',
    timeforcomp: 'সমাপ্তির জন্য সময় অনুমান',
    reset: 'রিসেট',
    warning:
      'সতর্কতা: নতুন লক্ষ্য নির্ধারণ করলে সমস্যার সব গণনা জন্য সব গণনা পূর্বাবস্থায় ফিরে যায়।',
    youare: 'আপনি হয়',
    goalaway: 'আপনার লক্ষ্য থেকে হালুদ দূরে',
    Moksha: 'মোক্ষ',
    help: 'সাহায্য',
    Ok: 'ঠিক আছে',
    begin: 'শুরু',
    home: 'বাড়ি',
    edit: 'সম্পাদনা',
    helphead: 'মেডিটেশন ট্র্যাকার অ্যাপে স্বাগতম!',
    para1:
      'এই অ্যাপটি আপনার ধ্যানের প্রগতি ট্র্যাক করতে সহায়ক করে। ডিফল্ট লক্ষ্য নির্ধারিত 1,00,000 (এক লক্ষ), এবং মালায় পাথরের সংখ্যা 108 নির্ধারিত করা হয়েছে। আপনি পছন্দসই লক্ষ্য এবং মালা পাথরের সংখ্যা ব্যক্তিগত করতে পারেন পরিস্থিতি স্ক্রিনে। আপডেট করা যখনই আপনি এই আঙ্কগুলি পরিবর্তন করেন, অ্যাপটি তারা আপনার লক্ষ্য অর্জন করতে প্রয়োজনীয় মালাদের মোট সংখ্যা ক্যালকুলেট করে।',
    para2:
      'আপনি যখন আপনার ধ্যান শুরু করেন, তখন টাইমার স্বয়ংভাবে চালু হয়ে যায়। আপনি একটি বিরতি প্রয়োজন হলে, আপনি শুধুমাত্র পজ বোতামে ট্যাপ করুন। আপনি আপনার ধ্যান পুনরারম্ভ করলে টাইমার স্বয়ংভাবে আবার চালু হবে। আপনি যদি দিনের জন্য শেষ করেন, তবে পিছনে ফিরতে ব্যক্তিগত সক্রিয় স্ক্রিনে পাঠান ট্যাপ করুন, যা আপনার ধ্যান প্রগতির পরিসংখ্যান দেখায়। এটা প্রয়োজনের উল্লিখিত করে আপনার গড় ধ্যানের সময় ভিত্তিক আপনার লক্ষ্য অর্জনের জন্য বাকি সময়ের আনুমান দেয়।',
    para3:
      'অ্যাপটি আপনাকে আপনার চোখ বন্ধ করে ধ্যান ধরার অনুমতি দেয়। একটি বিপ শব্দ একটি মালার সমাপ্তি দেওয়ার জন্য নির্দেশ করে, এবং একটি পৃথক টোন দ্বারা নির্দেশ করে যে আপনি আপনার লক্ষ্যে পৌঁছে গেছেন। সম্পাদিত মালার গণনা সবসময় প্রধান স্ক্রিনে দেওয়া হয়।',
    para4:
      'ধ্যানের বিশ্বে আপনাকে স্বাগতম! আপনার অভ্যন্তরীণ শান্তি এবং পরিপূর্ণতার দিকে আপনার প্রয়ান শুরু করুন।',
    elapsed: 'কাটানো সময়',
    more: 'অধিক',
    web: 'ওয়েব অ্যাপস',
    tnc: 'অ্যাপ নীতি',
    info: 'সম্পর্কে',
    share: 'শেয়ার করুন',
    settings: 'সেটিংস',
    appshead: 'অ্যাপ গোপনীয়তা নীতি',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'এখন লক্ষ্যের সময় মূল্যায়ন করা সম্ভব নয়।',
    snack1: 'জপ মালা\n কম মৌখিক হলে 11 সিট',
    snack2: 'জপ মালা\n সর্বনিম্ন লক্ষ্য 108',
    cancel: 'বাতিল করুন',
    dismiss: 'খোকান',
    warning1: 'আপনি আপনার লক্ষ্য পূরণ করেছেন\n সেটিংস শূন্যে রিসেট হচ্ছে',
    settingssave: 'সেটিংস সেভ করা হয়েছে!',
    ahe: '',
  },
  {
    appname: 'जपमाला',
    label: 'மொழி தேர்ந்தெடு',
    selectlanguage: 'Select Language(மொழி தேர்ந்தெடு)',
    setyourtarget: 'உங்கள் இலக்குக்கை அமை',
    default: 'இயல்புநிலை',
    malabeads: 'மாலா கல்லுக்கள்',
    save: 'சேமி',
    meditaionsofar: 'இப்போது தியான',
    totalcount: 'மொத்த எண்ணிக்கை',
    target: 'இலக்கு',
    beadcont: 'மாலா மணிக்கழியாக',
    malascomp: 'மாலா முடிந்தன',
    timeforcomp: 'நிறைய நேரம் முடிந்துவிடுதல் மதிப்பெண்',
    reset: 'மீட்டமை',
    warning:
      'எச்சரிக்கை: புதிய இலக்கை அமைக்கும்போது அனைத்து எண்களையும் பூட்டி வைத்து முதல் வரை அனைத்து எண்கள் பூட்டப்படும்.',
    youare: 'நீ',
    goalaway: 'உங்கள் இலக்குக்கு கிடைக்கும் வெற்றியிலிருக்கின்றீர்கள்',
    Moksha: 'மோக்ஷா',
    help: 'உதவி',
    Ok: 'சரி',
    begin: 'ஆரம்பி',
    home: 'வீடு',
    edit: 'திருத்து',
    helphead: 'தியான டிராக்கர் ஆப் குரல்!',
    para1:
      'இந்த ஆப் உங்கள் தியான முன் நடத்தல் பரிசோதிக்க உதவுகின்றது. இயல்புநிலை இலக்கு 1,00,000 (ஒரு இலட்சம்) ஆக அமைக்கப்பட்டுள்ளது, மற்றும் மாலாவில் உள்ள கல்லுக்களின் எண்ணை 108 ஆக அமைக்கப்பட்டுள்ளது. நீங்கள் விரும்பும் இலக்குக்கு மற்றும் மாலா மணிக்கழியாக எண்ணிக்கையை உங்களது ஆராய்ச்சி திரையில் விரிவாக அமைக்கலாம். இந்த ஆப் இந்த எண்களை மாற்றும்போது உங்கள் லக்ஷ்யத்தை பெற வேண்டிய மாலாகளின் மொத்த எண்களை உருவாக்கும்.',
    para2:
      'நீங்கள் உங்கள் தியானத்தை தொடங்கும்போது, டைமர் தானாக ஆரம்பப்படும். விரம்பப்பட்டிருக்கின்றதால் விரம்பவும் தடை பொத்தாக தடை பொத்தாக அழுத்தவும் தேவைப்பட்டால், பருத்தி பட்டனை அழுத்தவும். உங்கள் தியானத்தை மீண்டும் தொடங்க வேண்டியதால், டைமர் தானாக மீண்டும் ஆரம்பப்படும். நீங்கள் நாள் முடித்ததால், திரும்பி முதல் திரைக்கு அழுத்தவும், அதில் உங்கள் தியான பரிசோதியின் பரிஸ்஥ிதியைக் காட்டுகின்ற புரட்சியைக் காட்டுகின்றது. அது உங்கள் சராசரி தியான காலத்தின் பார்வையில் உங்கள் இலக்குக்கு எதிர்காலம் பெற உதவுகின்றது.',
    para3:
      'இந்த ஆப் உங்கள் கண்கள் மூடிய நிலையில் தியானம் செய்ய அனுமதிக்குகின்றது. ஒரு மாலா முடிந்ததை ஒரு குறிப்பு ஒலியாக காட்டுகின்றது, மற்றும் ஒரு வேறு மனிதரின் லக்ஷ்யத்துக்கு வர்த்திகையாக காட்டுகின்றது. முடிந்த மாலாகளின் எண்ணிக்கை முக்கியமாகப் பார்க்கப்படுகின்றது.',
    para4:
      'தியானத்தின் உலகத்தில் வருக! உள்ளே சாந்தி மற்றும் உணர்வுக்கு உங்கள் பயணத்தை தொடங்கவும்.',
    elapsed: 'கழிந்த நேரம்',
    more: 'மேலும்',
    web: 'வலை வலைப்பதிவுகள்',
    tnc: 'பயன்பாடு கொள்கை',
    info: 'பற்றி',
    share: 'பகிர்',
    settings: 'அமைப்புகள்',
    appshead: 'பயன்பாடு தனியுறத்தை குறித்த கொள்கை',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'இப்போது இல்லை: லக்ஷ்ய நேரம் கருத முடியாது.',
    snack1: 'ஜப மாலா\n குழந்தை எண் குறைவாக 11',
    snack2: 'ஜப மாலா\n குறைவான இலக்கை 108',
    cancel: 'ர஦்஦ு செய்',
    dismiss: 'திராட்டு',
    warning1:
      'உங்கள் இலக்ஷியத்தை நீங்கள் முடித்துவிட்டீர்கள்\n பூட்டிக்கொள்ள வேண்டும்',
    settingssave: 'அமைப்புகள் சேமிக்கப்பட்டன!',
    ahe: '',
  },
  {
    label: 'Français',
    selectlanguage: 'Select Language(Choisir la langue)',
    setyourtarget: 'Définissez votre objectif',
    default: 'Défaut',
    malabeads: 'Perles de Mala',
    save: 'Sauvegarder',
    meditaionsofar: "Méditation jusqu'à présent",
    totalcount: 'Total',
    target: 'Cible',
    beadcont: 'Compte de perles',
    malascomp: 'Mala terminés',
    timeforcomp: 'Estimation du temps pour la complétion',
    reset: 'Réinitialiser',
    warning:
      "Avertissement : Le réglage d'un nouvel objectif réinitialise tous les compteurs à zéro.",
    youare: 'Vous êtes',
    goalaway: 'perles loin de votre objectif',
    Moksha: 'Moksha',
    help: 'Aide',
    Ok: "D'accord",
    begin: 'Commencer',
    home: 'Accueil',
    edit: 'Modifier',
    helphead: "Bienvenue dans l'application de suivi de la méditation !",
    para1:
      "Cette application vous aide à suivre votre progression en méditation. L'objectif par défaut est fixé à 1,00,000 (cent mille), et le nombre de perles dans un Mala est fixé à 108. Vous pouvez personnaliser votre objectif préféré et le compte de perles Mala sur l'écran des paramètres. L'application calcule instantanément le nombre total de Malas nécessaires pour atteindre votre objectif chaque fois que vous modifiez ces chiffres.",
    para2:
      "Lorsque vous commencez votre méditation, le minuteur démarre automatiquement. Si vous avez besoin d'une pause, appuyez simplement sur le bouton Pause. Le minuteur reprend automatiquement lorsque vous redémarrez votre méditation. Si vous avez terminé pour la journée, appuyez sur le bouton Retour pour revenir à l'écran d'ouverture, qui affiche les statistiques de votre progression en méditation jusqu'à présent. Il fournit également une estimation du temps restant pour atteindre votre objectif, en fonction de votre durée moyenne de méditation.",
    para3:
      "L'application vous permet de méditer les yeux fermés. Un son de bip indique l'achèvement d'un Mala, et un ton différent signifie que vous avez atteint votre objectif. Le nombre de Malas complétés est toujours affiché sur l'écran principal.",
    para4:
      'Bienvenue dans le monde de la méditation ! Commencez votre voyage vers la paix intérieure et la pleine conscience.',
    elapsed: 'Temps écoulé',
    more: 'Plus',
    web: 'Applications Web',
    tnc: 'Politique des Applications',
    info: 'À Propos',
    share: 'Partager',
    settings: 'Paramètres',
    appshead: 'Politique de Confidentialité des Applications',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: "Impossible d'estimer le temps de l'objectif pour le moment.",
    snack1: 'Japa Mala\n Le nombre minimum de perles est de 11',
    snack2: "Japa Mala\n L'objectif minimum est de 108",
    cancel: 'Annuler',
    dismiss: 'Rejeter',
    warning1: 'Vous avez atteint votre objectif\n remise à zéro',
    settingssave: 'Paramètres enregistrés !',
    ahe: '',
  },
];
