export const lang = [
  {
    appname: 'Japa Mala',
    label: 'Select Language',
    selectlanguage: 'Select Language',
    setyourtarget: 'Set Your Target',
    default: 'Default',
    malabeads: 'Mala Beads',
    save: 'Save',
    meditaionsofar: 'Meditation So Far',
    totalcount: 'Total Count',
    target: 'Target',
    beadcont: 'Beads Count',
    malascomp: 'Mala Completed',
    timeforcomp: 'Time estimation for completion',
    reset: 'Reset',
    resetm: 'Reset',
    warning: 'Warning: Setting new target resets all counters to Zero.',
    youare: 'You are',
    goalaway: 'malas away from your goal',
    Moksha: 'Moksha',
    help: 'Help',
    Ok: 'Ok',
    begin: 'Begin',
    home: 'Home',
    edit: 'Edit',
    helphead: 'Welcome to the Japa Mala',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'Elapsed Time',
    more: 'More Apps',
    web: 'Web Apps',
    tnc: 'Apps Policy',
    info: 'About',
    share: 'Share',
    settings: 'Settings',
    appshead: 'Apps Privacy Policy',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'Cannot estimate goal time now',
    snack1: 'Japa Mala\n Minimum number of beads is 11',
    snack2: 'Japa Mala\n Minimum Target is 108',
    cancel: 'Cancel',
    dismiss: 'Dismiss',
    warning1: 'You have completed your target\n resetting to zero',
    settingssave: 'Settings Saved!',
    ahe: '',
  },
  {
    appname: 'जपमाला',
    label: 'मराठी',
    selectlanguage: 'Select Language(भाषा निवडा)',
    setyourtarget: 'आपले लक्ष्य',
    default: 'डिफ़ॉल्ट',
    defaultm: 'मण्यांची किमान संख्या',
    malabeads: 'मणी',
    save: 'जतन',
    meditaionsofar: 'आतापर्यंत चे ध्यान',
    totalcount: 'एकूण संख्या',
    target: 'लक्ष्य',
    beadcont: 'मणी मोजणे',
    malascomp: 'पूर्ण झालेल्या माळा',
    timeforcomp: 'तुमचे ध्येय गाठण्यासाठी अंदाजे वेळ',
    reset: 'रीसेट',
    resetm: 'ठीक आहे',
    warning: 'सूचना: नवीन लक्ष्य सेट केल्याने सर्व काउंटर शून्य करते.',
    youare: 'तुम्ही तुमच्या ध्येयापासून',
    goalaway: 'माळा दूर आहात',
    Moksha: 'मोक्ष',
    help: 'मदत',
    Ok: 'ठीक',
    begin: 'प्रारंभ',
    home: 'होम',
    edit: 'संपादित करा',
    helphead: 'ध्यान ट्रॅकर अ‍ॅपमध्ये आपले स्वागत आहे!',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'साधनेचा वेळ',
    more: 'अजून अॅप्स',
    web: 'वेब अ‍ॅप्स',
    tnc: 'अॅप्स धोरण',
    info: 'अॅप्स संबांधित ',
    share: 'इतरांना द्या',
    settings: 'सेटिंग्ज',
    appshead: 'अॅप्स धोरण',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'तुमच्या ध्येयाच्या वेळेचा अंदाज आत्ता लावू शकत नाही.',
    snack1: 'जप माला\n 11 वर्षीय आवश्यक असलेली किंमत',
    snack2: 'जप माला\n 108 वर्षीय नियमितीस आवश्यक आहे',
    cancel: 'रद्द करा',
    dismiss: 'ठीक आहे',
    warning1: 'तुम्ही आपल्या उद्देश्याला पूर्ण केलं आहे\n निरूपणात आणता येईल',
    settingssave: 'सेटिंग्ज सेव्ह केली!',
    ahe: 'आहे',
  },
  {
    label: 'भाषा चुनें',
    selectlanguage: 'Select Language(भाषा चुनें)',
    setyourtarget: 'अपना लक्ष्य',
    default: 'डिफ़ॉल्ट',
    defaultm: 'मानकों की न्यूनतम संख्या ',
    malabeads: 'मनका',
    save: 'जतन',
    meditaionsofar: 'अब तक का ध्यान',
    totalcount: 'कुल गिनती',
    target: 'लक्ष्य',
    beadcont: 'मनका गिनती',
    malascomp: 'पूर्ण हुई मालाए',
    timeforcomp: 'अपने लक्ष्य तक पहुंचने का अनुमानित समय',
    reset: 'रीसेट',
    resetm: ' ठीक है',
    warning:
      'चेतावनी: नया लक्ष्य निर्धारित करने से सभी काउंटर शून्य हो जाते हैं।',
    youare: 'आप अपने लक्ष्य से ',
    goalaway: 'माला दूर हैं',
    Moksha: 'मोक्ष',
    help: 'मदद',
    Ok: 'ठीक',
    begin: 'आरंभ',
    home: 'होम',
    edit: 'समायोजन',
    helphead: 'ध्यान ट्रैकर ऐप में आपका स्वागत है!',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'साधना समय',
    more: 'और ऐप',
    web: 'वेब ऐप्स',
    tnc: 'ऐप्स नीति',
    info: 'अॅप्स संबांधित',
    share: 'इतरांना द्या',
    settings: 'सेटिंग्स',
    appshead: 'गोपनियता',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'अभी अपने लक्ष्य के समय का अनुमान नहीं लगाया जा सकता।',
    snack1: 'जपमाला\n 11 मनी की न्यूनतम संख्या है',
    snack2: 'जपमाला\n 108 का न्यूनतम लक्ष्य है',
    cancel: 'रद्द करें',
    dismiss: 'ठीक है',
    warning1: 'आपने अपना लक्ष्य पूरा किया है\n शून्य पर रीसेट किया जा रहा है',
    settingssave: 'सेटिंग सहेजी गई!',
    ahe: 'है',
  },
  {
    appname: 'જપમાલા',
    label: 'ભાષા પસંદ કરો',
    selectlanguage: 'ભાષા પસંદ કરો',
    setyourtarget: 'તમારું લક્ષ્ય',
    default: 'મૂળભૂત',
    malabeads: 'માળા બીડ્સ',
    save: 'સાચવો',
    meditaionsofar: 'ધ્યાન અત્યંત',
    totalcount: 'કુલ ગણાય',
    target: 'લક્ષ્ય',
    beadcont: 'માળાના બીડ્સ',
    malascomp: 'માળા પૂર્ણ થયો',
    timeforcomp: 'પૂર્ણ થવાનો સમય અંદાજ',
    reset: 'રીસેટ',
    warning: 'ચેતવણી: નવો લક્ષ્ય સેટ કરવાથી તમામ ગણતરીઓ શૂન્ય થયો છે.',
    youare: 'તમે',
    goalaway: 'તમારા લક્ષ્યથી માળા દૂર છો',
    Moksha: 'મોક્ષ',
    help: 'મદદ',
    Ok: 'ઠીક છે',
    begin: 'શરૂ',
    home: 'ઘર',
    edit: 'ફેરફાર કરો',
    helphead: 'ધ્યાન ટ્રેકર એપ્લિકેશનમાં આપનું સ્વાગત છે!',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'કામ થયેલ સમય',
    more: 'વધુ એપ',
    web: 'વેબ એપ્લિકેશન્સ',
    tnc: 'એપ નીતિ',
    info: 'વિગતો',
    share: 'શેર કરો',
    settings: 'સેટિંગ્સ',
    appshead: 'એપ્લિકેશન્સ ગોપન નીતિ',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'હમણાં લક્ષ્ય સમય આંકવું શક્ય નથી.',
    snack1: 'જપા માળા\n 11 અથવા તેના નીચેના મણ્યોની મિનિમમ સંખ્યા 11 છે',
    snack2: 'જપા માળા\n ન્યૂનતમ લક્ષ્ય 108 છે',
    cancel: 'રદ કરો',
    dismiss: 'ખારીજ કરો',
    warning1: 'તમે તમારું લક્ષ્ય પૂરુ કર્યું છે\n શૂન્ય પર રીસેટ કરવામાં આવશે',
    settingssave: 'સેટિંગ્સ સેવ કરી!',
    ahe: '',
  },
  {
    label: 'বাঙালি',
    selectlanguage: 'Select Language(ভাষা নির্বাচন করুন)',
    setyourtarget: 'আপনার লক্ষ্য নির্ধারণ করুন',
    default: 'ডিফল্ট',
    malabeads: 'মালা হালুদ',
    save: 'সংরক্ষণ',
    meditaionsofar: 'এখন পর্যন্ত ধ্যান',
    totalcount: 'মোট গণনা',
    target: 'লক্ষ্য',
    beadcont: 'মালা হালুদের সংখ্যা',
    malascomp: 'মালা সমাপ্ত',
    timeforcomp: 'সমাপ্তির জন্য সময় অনুমান',
    reset: 'রিসেট',
    warning:
      'সতর্কতা: নতুন লক্ষ্য নির্ধারণ করলে সমস্যার সব গণনা জন্য সব গণনা পূর্বাবস্থায় ফিরে যায়।',
    youare: 'আপনি হয়',
    goalaway: 'আপনার লক্ষ্য থেকে হালুদ দূরে',
    Moksha: 'মোক্ষ',
    help: 'সাহায্য',
    Ok: 'ঠিক আছে',
    begin: 'শুরু',
    home: 'বাড়ি',
    edit: 'সম্পাদনা',
    helphead: 'মেডিটেশন ট্র্যাকার অ্যাপে স্বাগতম!',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'কাটানো সময়',
    more: 'অধিক',
    web: 'ওয়েব অ্যাপস',
    tnc: 'অ্যাপ নীতি',
    info: 'সম্পর্কে',
    share: 'শেয়ার করুন',
    settings: 'সেটিংস',
    appshead: 'অ্যাপ গোপনীয়তা নীতি',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'এখন লক্ষ্যের সময় মূল্যায়ন করা সম্ভব নয়।',
    snack1: 'জপ মালা\n কম মৌখিক হলে 11 সিট',
    snack2: 'জপ মালা\n সর্বনিম্ন লক্ষ্য 108',
    cancel: 'বাতিল করুন',
    dismiss: 'খোকান',
    warning1: 'আপনি আপনার লক্ষ্য পূরণ করেছেন\n সেটিংস শূন্যে রিসেট হচ্ছে',
    settingssave: 'সেটিংস সেভ করা হয়েছে!',
    ahe: '',
  },
  {
    appname: 'जपमाला',
    label: 'மொழி தேர்ந்தெடு',
    selectlanguage: 'Select Language(மொழி தேர்ந்தெடு)',
    setyourtarget: 'உங்கள் இலக்குக்கை அமை',
    default: 'இயல்புநிலை',
    malabeads: 'மாலா கல்லுக்கள்',
    save: 'சேமி',
    meditaionsofar: 'இப்போது தியான',
    totalcount: 'மொத்த எண்ணிக்கை',
    target: 'இலக்கு',
    beadcont: 'மாலா மணிக்கழியாக',
    malascomp: 'மாலா முடிந்தன',
    timeforcomp: 'நிறைய நேரம் முடிந்துவிடுதல் மதிப்பெண்',
    reset: 'மீட்டமை',
    warning:
      'எச்சரிக்கை: புதிய இலக்கை அமைக்கும்போது அனைத்து எண்களையும் பூட்டி வைத்து முதல் வரை அனைத்து எண்கள் பூட்டப்படும்.',
    youare: 'நீ',
    goalaway: 'உங்கள் இலக்குக்கு கிடைக்கும் வெற்றியிலிருக்கின்றீர்கள்',
    Moksha: 'மோக்ஷா',
    help: 'உதவி',
    Ok: 'சரி',
    begin: 'ஆரம்பி',
    home: 'வீடு',
    edit: 'திருத்து',
    helphead: 'தியான டிராக்கர் ஆப் குரல்!',
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'கழிந்த நேரம்',
    more: 'மேலும்',
    web: 'வலை வலைப்பதிவுகள்',
    tnc: 'பயன்பாடு கொள்கை',
    info: 'பற்றி',
    share: 'பகிர்',
    settings: 'அமைப்புகள்',
    appshead: 'பயன்பாடு தனியுறத்தை குறித்த கொள்கை',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: 'இப்போது இல்லை: லக்ஷ்ய நேரம் கருத முடியாது.',
    snack1: 'ஜப மாலா\n குழந்தை எண் குறைவாக 11',
    snack2: 'ஜப மாலா\n குறைவான இலக்கை 108',
    cancel: 'ர஦்஦ு செய்',
    dismiss: 'திராட்டு',
    warning1:
      'உங்கள் இலக்ஷியத்தை நீங்கள் முடித்துவிட்டீர்கள்\n பூட்டிக்கொள்ள வேண்டும்',
    settingssave: 'அமைப்புகள் சேமிக்கப்பட்டன!',
    ahe: '',
  },
  {
    label: 'Français',
    selectlanguage: 'Select Language(Choisir la langue)',
    setyourtarget: 'Définissez votre objectif',
    default: 'Défaut',
    malabeads: 'Perles de Mala',
    save: 'Sauvegarder',
    meditaionsofar: "Méditation jusqu'à présent",
    totalcount: 'Total',
    target: 'Cible',
    beadcont: 'Compte de perles',
    malascomp: 'Mala terminés',
    timeforcomp: 'Estimation du temps pour la complétion',
    reset: 'Réinitialiser',
    warning:
      "Avertissement : Le réglage d'un nouvel objectif réinitialise tous les compteurs à zéro.",
    youare: 'Vous êtes',
    goalaway: 'perles loin de votre objectif',
    Moksha: 'Moksha',
    help: 'Aide',
    Ok: "D'accord",
    begin: 'Commencer',
    home: 'Accueil',
    edit: 'Modifier',
    helphead: "Bienvenue dans l'application de suivi de la méditation !",
    para1: 'This App helps you track your meditation. ',
    para2:
      ' The default goal is set to 1,00,000 (One lac) and the number of beads in Mala is set to 108. You may set your preferred goal with a Mala bead count of your choice on the Settings screen. Whenever you change these figures, the total number of Malas required to achieve the goal is instantaneously computed. ',
    para3:
      'As you start your meditation, the timer starts ticking automatically. If you need a break, just hit the Pause button. The timer would continue automatically when you restart meditation. If you are done for the day, just hit Back button and you will come to the opening screen which displays the statistics of your meditation so far. It also estimates the time remaining to achieve your goal by considering the average time you took so far. ',
    para4:
      'Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    para5: 'Welcome to the world of Meditation!',
    elapsed: 'Temps écoulé',
    more: 'Plus',
    web: 'Applications Web',
    tnc: 'Politique des Applications',
    info: 'À Propos',
    share: 'Partager',
    settings: 'Paramètres',
    appshead: 'Politique de Confidentialité des Applications',
    appspara1:
      'By using this app you agree to the terms of this privacy policy.',
    appspare2:
      'Our app "Japa Mala" does not collect nor transmit the user\'s personal information.',
    appspare3:
      'No personal information is used, stored, secured or disclosed by services this application works with.',
    appspara4: 'Internet is only used to connect and display Advertisements.',
    appspara5:
      'This app does not warrant the completeness, timeliness or accuracy of any of the data contained in the app.',
    appspara6:
      'All information conveyed hereby is provided to users "AS IS". In no event shall “ABCOM” be liable for any damages of any kind related to the use or misuse of information provided hereby.',
    appspara7:
      'ABCOM makes no warranty that the results may be obtained from the use of the service will be accurate or reliable, the service will meet your requirements, the service will be uninterrupted, timely, secure, or error-free or any errors in the service will be corrected.',
    appspara8:
      'If you have any questions about this app, or if you require any support, you can send us an email at support@abcom. com including the app name.',
    cannot: "Impossible d'estimer le temps de l'objectif pour le moment.",
    snack1: 'Japa Mala\n Le nombre minimum de perles est de 11',
    snack2: "Japa Mala\n L'objectif minimum est de 108",
    cancel: 'Annuler',
    dismiss: 'Rejeter',
    warning1: 'Vous avez atteint votre objectif\n remise à zéro',
    settingssave: 'Paramètres enregistrés !',
    ahe: '',
  },
];
