export const lang = [
  {
    label: 'Select Language',
    selectlanguage: 'Select Language',
    setyourtarget: 'Set Your Target',
    default: 'Default',
    malabeads: 'Mala Beads',
    save: 'Save',
    meditaionsofar: 'Meditation So Far',
    totalcount: 'Total Count',
    target: 'Target',
    beadcont: 'Beads Count',
    malascomp: 'Mala Completed',
    timeforcomp: 'Time estimation for completion',
    reset: 'Reset',
    warning: 'Warning: Setting new target resets all counters to zero.',
    youare: 'You are',
    goalaway: 'malas away from your goal',
    Moksha: 'Moksha',
    help: 'Help',
    Ok: 'Ok',
    begin: 'Begin',
    home: 'Home',
    edit: 'Edit',
    helphead: 'Welcome to the Meditation Tracker App!',
    para1:
      'This app helps you track your meditation progress. The default goal is set to 1,00,000 (One lac), and the number of beads in a Mala is set to 108. You can customize your preferred goal and Mala bead count on the Settings screen. The app instantly calculates the total number of Malas required to achieve your goal whenever you modify these figures.',
    para2:
      ' When you start your meditation, the timer begins automatically. If you need a break, simply tap the Pause button. The timer will resume automatically when you restart your meditation. If you have finished for the day, tap the Back button to return to the opening screen, which displays statistics of your meditation progress so far. It also provides an estimate of the remaining time to achieve your goal, based on your average meditation duration.',
    para3:
      'The app allows you to meditate with your eyes closed. A beep sound indicates the completion of a Mala, and a different tone signifies when you have reached your goal. The completed Mala count is always displayed on the main screen.',
    para4:
      '  Welcome to the world of Meditation! Start your journey to inner peace and mindfulness.',
    elapsed: 'Elapsed Time',
    more: 'More',
    web: 'Web Apps',
  },
  {
    label: 'भाषा चुनें',
    selectlanguage: 'भाषा चुनें',
    setyourtarget: 'अपना लक्ष्य सेट करें',
    default: 'डिफ़ॉल्ट',
    malabeads: 'माला बीड्स',
    save: 'सेव',
    meditaionsofar: 'अब तक की ध्यान साधना',
    totalcount: 'कुल गिनती',
    target: 'लक्ष्य',
    beadcont: 'माला के मनके',
    malascomp: 'माला पूरी हुई',
    timeforcomp: 'पूरा होने का समय अनुमान',
    reset: 'रीसेट',
    warning: 'चेतावनी: नई लक्ष्य सेट करने पर सभी गिनती शून्य हो जाती हैं।',
    youare: 'आप',
    goalaway: 'माला आपके लक्ष्य से दूर हैं',
    Moksha: 'मोक्ष',
    help: 'मदद',
    Ok: 'ठीक है',
    begin: 'आरंभ',
    home: 'होम',
    edit: 'बदलाव करें',
    helphead: 'ध्यान ट्रैकर ऐप में आपका स्वागत है!',
    para1:
      'यह ऐप आपकी ध्यान प्रगति का ट्रैक करने में मदद करता है। डिफ़ॉल्ट लक्ष्य 1,00,000 (एक लाख) पर सेट किया गया है, और माला में बीड्स की संख्या 108 पर सेट की गई है। आप सेटिंग्स स्क्रीन पर अपने पसंदीदा लक्ष्य और माला बीड्स गिनती को अनुकूल कर सकते हैं। जब आप इन आंकड़ों को संशोधित करते हैं, ऐप तुरंत आपके लक्ष्य को प्राप्त करने के लिए आवश्यक मालाओं की कुल संख्या की गणना करता है।',
    para2:
      'जब आप अपना ध्यान शुरू करते हैं, तो टाइमर स्वचालित रूप से चालू होता है। यदि आपको विश्रांति की आवश्यकता है, तो बस पॉज़ बटन दबाएं। जब आप अपना ध्यान दोबारा शुरू करते हैं, तो टाइमर स्वचालित रूप से फिर से शुरू हो जाएगा। यदि आप दिन के लिए समाप्त हो गए हैं, तो वापस जाने के लिए बैक बटन दबाएं, जिसमें आपकी ध्यान साधना की प्रगति के सांख्यिकी दिखाई देती है। यह आपकी औसत ध्यान अवधि के आधार पर आपके लक्ष्य को पूरा करने के लिए शेष समय का अनुमान भी देता है।',
    para3:
      'ऐप आपको आपके आंखें बंद करके ध्यान करने की अनुमति देता है। एक बीप की आवाज़ द्वारा सूचित किया जाता है कि एक माला पूरी हो गई है, और एक विभिन्न ध्वनि द्वारा सूचित किया जाता है कि आपने अपना लक्ष्य प्राप्त कर लिया है। पूरी हुई माला की गिनती हमेशा मुख्य स्क्रीन पर दिखाई देती है।',
    para4:
      'ध्यान की दुनिया में आपका स्वागत है! आंतरिक शांति और सजगता की ओर अपनी यात्रा शुरू करें।',
    elapsed: 'बिता हुआ समय',
    more: 'और भी',
    web: 'वेब ऐप्स',
  },
];
