export { default as Head } from './header';
export { default as Foot } from './footer';
export { default as Soundback } from './sound';
export { default as Loading } from './loading';
export { default as Langsel } from './langselector';
export { default as Ads } from './adsfullscreen';
export { default as Smoke } from './smoke';
export { default as Sidemenu } from './sidemenu';
export { default as Cmodal } from './custommodal';
